require 'rubygems'
require 'gosu'
require 'rmagick'

require_relative './tunables'
require_relative './pausable'
require_relative './sprites'
require_relative './game_state'
require_relative './square'
require_relative './piece'
require_relative './next_piece'
require_relative './main_board'
require_relative './tetris_window'
